development: &dev
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: crawler_development

test:
  <<: *dev

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: crawler_production
